### ISSUE TITLE
the odin project

### ISSUE THREAD

**Issue by sametkayik** [SelmanKahya/turkcedev-docs#2]
the odin project benzeri bir site mi olacak bilmiyorum ama öyle değilse de bence buna bir göz atabilirsiniz. yol gösterme açısından güzel sitelerden birisi. balık vermiyor, tutmayı öğretiyor. 

https://www.theodinproject.com/tracks/2

**Comment by SelmanKahya** [comment]
tesekkurler, kesinlikle detayli bir sekilde inceleyecegim.
